### ISSUE TITLE
M5Stack classic (and other ESP32 without psram builds) support

### ISSUE THREAD

**Issue by tobozo** [CelliesProjects/M5AnalogClock#1]
hey and thanks for this amazing project :-)

I just got it working with "M5Stack-core-esp32" board selection.

All it needed was to add this in the setup() : 

    clockSprite.setColorDepth( 8 );

(inserted just before this:)

    clockSprite.createSprite( 240, 320 );

[edit] bonus is you get more FPS when compiled for M5Classic as TFT_eSprites are much slower when using psram !

Also there's not much to change in TFTShape to get it to work with M5Stack.h or ESP32-Chimera-Core, only one file needs to be edited (TFTShape.h):

![image](https://user-images.githubusercontent.com/1893754/73100928-e5659600-3eee-11ea-8856-a7f8eb670569.png)

**Comment by CelliesProjects** [comment]
Hi tobozo! 
Thanks for the bugfix.
Will be implemented soon.
